import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

export default new Vuex.Store({
    state:{
      equipmentModels:[],
      equipments:[],
      users:[],
      storages:[],
      equipmentModel:{
        emId:'',
        emName:'',
        emModel:'',
        emRemake:''
      },
      equipment:{
        eId:'',
        eStatus:'',
        eStorageStatus:'',
        emId:'',
        eRemake:'',
        equipmentModel:{
          emName:'',
          emModel:''
        }
      },
      user:{
        userId:"",
        userPosition:"",
        userRealName:"",
        userBirthday:"",
        userTel:"",
        userAccount:"",
        userSex:"",
        userEmail:"",
        userAddress:"",
        userRegisteredTime:"",
        lastIp:"",
        lastTime:"",
      },
      loginUser:{
        userRealName:null,
        userId:null,
        userName:null,
        userTel:null,
        userAddress:null,
        userPosition:null,
        userAccount:null,
        lastTime:null
      },
      equipmentTrade:{
        userId:'',
        userRealName:'',
        emModel:'',
        emName:'',
        eId:'',
        userTel:'',
        etDdl:'',
      },
      storage:{
        inStorage:'',
        totalStorage:'',
        equipment:{
          eId:'',
          equipmentModel:{
            emId:'',
            emName:'',
            emModel:''
          }
        }
      },
      success:{
        id:'',
        startPage:''
      },
    },
  mutations:{
      setEquipmentModel(state,equipmentModel){
        this.state.equipmentModel=equipmentModel;
      },
    setEquipmentModels(state,equipmentModels){
        this.state.equipmentModels=equipmentModels;
      },
    setLoginUser(state,loginUser){
        this.state.loginUser=loginUser;
      console.log('保存用户信息');
    },
    setUser(state,User){
        this.state.User=User;
        },
    setUsers(state,Users){
      this.state.Users=Users;
    },
    setEquipments(state,equipments){
        this.state.equipments=equipments;
    },
    setEquipment(state,equipment){
        this.state.equipment=equipment;
    },
    setEquipmentTrade(state,equipmentTrade){
        this.state.equipmentTrade=equipmentTrade;
    },
    setStorages(state,storages){
        this.state.storages = storages;
    },
    setSuccess(state,success){
      this.state.success = success;
    }
  }
});
